'use client'

import { useState, useRef, useEffect, useCallback } from 'react'
import {
  Button,
  CopyButton,
  DownloadButton,
  Field,
  TextArea,
  TextInput,
  Select,
  Toolbar,
  IO,
  Panel,
} from '@/components/ui/kit'

/* ── random helpers ──────────────────────────────────────────────────────── */

function randInt(min: number, max: number): number {
  const arr = new Uint32Array(1)
  crypto.getRandomValues(arr)
  return min + (arr[0] % (max - min + 1))
}

function randFloat(min: number, max: number): number {
  const arr = new Uint32Array(1)
  crypto.getRandomValues(arr)
  return min + (arr[0] / 0xffffffff) * (max - min)
}

function pickFrom<T>(arr: T[]): T {
  return arr[randInt(0, arr.length - 1)]
}

function uuidv4(): string {
  if (typeof crypto.randomUUID === 'function') return crypto.randomUUID()
  const b = new Uint8Array(16)
  crypto.getRandomValues(b)
  b[6] = (b[6] & 0x0f) | 0x40
  b[8] = (b[8] & 0x3f) | 0x80
  const h = Array.from(b).map((x) => x.toString(16).padStart(2, '0'))
  return [h.slice(0,4).join(''), h.slice(4,6).join(''), h.slice(6,8).join(''), h.slice(8,10).join(''), h.slice(10).join('')].join('-')
}

const FIRST_NAMES = ['Alice','Bob','Carol','David','Elena','Frank','Grace','Hiro','Iris','James','Kira','Liam','Maya','Noah','Olivia','Paulo','Quinn','Rosa','Sam','Tara']
const LAST_NAMES  = ['Adams','Baker','Chen','Diaz','Evans','Foster','Garcia','Hayes','Iyer','Jones','Kim','Lopez','Miller','Nguyen','Ortiz','Patel','Quinn','Ramos','Smith','Torres']
const DOMAINS     = ['example.com','testmail.io','fakemail.net','devtest.org','sample.co']

function randRecord(index: number): { id: string; name: string; email: string; date: string; amount: string } {
  const first = pickFrom(FIRST_NAMES)
  const last  = pickFrom(LAST_NAMES)
  const d     = new Date(randInt(1577836800000, 1735689600000)) // 2020-2025
  return {
    id:     String(index + 1),
    name:   `${first} ${last}`,
    email:  `${first.toLowerCase()}.${last.toLowerCase()}${randInt(1,99)}@${pickFrom(DOMAINS)}`,
    date:   d.toISOString().slice(0, 10),
    amount: randFloat(10, 9999).toFixed(2),
  }
}

function makeRecords(rows: number) {
  const n = Math.max(1, Math.min(500, rows))
  return Array.from({ length: n }, (_, i) => randRecord(i))
}

/* ── generators ─────────────────────────────────────────────────────────── */

function generateCSV(rows: number): string {
  const header = 'id,name,email,date,amount'
  const lines = makeRecords(rows).map(
    r => `${r.id},"${r.name}",${r.email},${r.date},${r.amount}`
  )
  return [header, ...lines].join('\n')
}

function generateJSON(rows: number): string {
  return JSON.stringify(makeRecords(rows), null, 2)
}

function generateXML(rows: number): string {
  const records = makeRecords(rows)
  const items = records
    .map(r =>
      `  <record>\n    <id>${r.id}</id>\n    <name>${r.name}</name>\n    <email>${r.email}</email>\n    <date>${r.date}</date>\n    <amount>${r.amount}</amount>\n  </record>`
    )
    .join('\n')
  return `<?xml version="1.0" encoding="UTF-8"?>\n<records>\n${items}\n</records>`
}

function generateHTML(): string {
  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>Sample Document</title>
  <style>
    body { font-family: sans-serif; max-width: 800px; margin: 2rem auto; padding: 0 1rem; color: #222; }
    h1   { border-bottom: 2px solid #c6f24e; padding-bottom: .4rem; }
    code { background: #f4f4f4; padding: 2px 6px; border-radius: 3px; }
  </style>
</head>
<body>
  <h1>Sample HTML Document</h1>
  <p>This is a <strong>generated</strong> HTML document created by the dauntexlabs File Generator tool.</p>
  <h2>Features</h2>
  <ul>
    <li>Semantic structure</li>
    <li>Minimal responsive layout</li>
    <li>Generated on <code>${new Date().toISOString()}</code></li>
  </ul>
  <p>Edit this template to suit your needs.</p>
</body>
</html>`
}

function generateMarkdown(): string {
  return `# Sample Markdown Document

> Generated by dauntexlabs File Generator — ${new Date().toISOString()}

## Introduction

This is a **sample Markdown document** with common formatting elements.

## Features

- Headings (h1–h4)
- **Bold** and _italic_ text
- Inline \`code\` and fenced blocks
- Ordered and unordered lists
- Blockquotes and horizontal rules

## Code Example

\`\`\`typescript
function greet(name: string): string {
  return \`Hello, \${name}!\`;
}

console.log(greet('world'));
\`\`\`

## Ordered List

1. First item
2. Second item
3. Third item

---

*End of sample document.*
`
}

function generatePlainText(): string {
  return `Sample Plain Text Document
Generated: ${new Date().toLocaleString()}
=============================

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod
tempor incididunt ut labore et dolore magna aliqua.

Section 1: Introduction
------------------------
This is a generated plain text document. It can serve as a placeholder,
test fixture, or template for your application.

Section 2: Data
---------------
ID:     ${uuidv4()}
Date:   ${new Date().toISOString()}
Source: dauntexlabs File Generator

Section 3: Notes
----------------
- Replace this content with your own data.
- The file is UTF-8 encoded.
- Line endings are LF (Unix-style).

=============================
End of document.
`
}

/* ── file type config ────────────────────────────────────────────────────── */

type FileType = 'csv' | 'json' | 'xml' | 'html' | 'markdown' | 'text' | 'png'

interface FileTypeConfig {
  label: string
  ext: string
  mime: string
  hasRows: boolean
  isText: boolean
}

const FILE_CONFIGS: Record<FileType, FileTypeConfig> = {
  csv:      { label: 'CSV',        ext: 'csv',  mime: 'text/csv',         hasRows: true,  isText: true  },
  json:     { label: 'JSON',       ext: 'json', mime: 'application/json', hasRows: true,  isText: true  },
  xml:      { label: 'XML',        ext: 'xml',  mime: 'application/xml',  hasRows: true,  isText: true  },
  html:     { label: 'HTML',       ext: 'html', mime: 'text/html',        hasRows: false, isText: true  },
  markdown: { label: 'Markdown',   ext: 'md',   mime: 'text/markdown',    hasRows: false, isText: true  },
  text:     { label: 'Plain Text', ext: 'txt',  mime: 'text/plain',       hasRows: false, isText: true  },
  png:      { label: 'PNG Image',  ext: 'png',  mime: 'image/png',        hasRows: false, isText: false },
}

const FILE_TYPE_OPTIONS = (Object.entries(FILE_CONFIGS) as [FileType, FileTypeConfig][]).map(
  ([value, { label }]) => ({ value, label })
)

/* ── PNG canvas generation ───────────────────────────────────────────────── */

const PNG_W = 600
const PNG_H = 400

function drawCanvas(canvas: HTMLCanvasElement) {
  const ctx = canvas.getContext('2d')
  if (!ctx) return

  canvas.width  = PNG_W
  canvas.height = PNG_H

  // Background
  ctx.fillStyle = '#0a0b09'
  ctx.fillRect(0, 0, PNG_W, PNG_H)

  // Acid border (4px inset)
  ctx.strokeStyle = '#c6f24e'
  ctx.lineWidth = 4
  ctx.strokeRect(2, 2, PNG_W - 4, PNG_H - 4)

  // Inner decorative frame
  ctx.strokeStyle = 'rgba(198,242,78,0.25)'
  ctx.lineWidth = 1
  ctx.strokeRect(20, 20, PNG_W - 40, PNG_H - 40)

  // Corner ticks
  const tick = 16
  ctx.strokeStyle = '#c6f24e'
  ctx.lineWidth = 2
  const corners: [number, number, number, number][] = [
    [20, 20, 20 + tick, 20], [20, 20, 20, 20 + tick],
    [PNG_W - 20, 20, PNG_W - 20 - tick, 20], [PNG_W - 20, 20, PNG_W - 20, 20 + tick],
    [20, PNG_H - 20, 20 + tick, PNG_H - 20], [20, PNG_H - 20, 20, PNG_H - 20 - tick],
    [PNG_W - 20, PNG_H - 20, PNG_W - 20 - tick, PNG_H - 20], [PNG_W - 20, PNG_H - 20, PNG_W - 20, PNG_H - 20 - tick],
  ]
  corners.forEach(([x1, y1, x2, y2]) => { ctx.beginPath(); ctx.moveTo(x1, y1); ctx.lineTo(x2, y2); ctx.stroke() })

  // Dimensions label
  ctx.fillStyle = '#c6f24e'
  ctx.font = 'bold 32px monospace'
  ctx.textAlign = 'center'
  ctx.textBaseline = 'middle'
  ctx.fillText(`${PNG_W} × ${PNG_H}`, PNG_W / 2, PNG_H / 2 - 22)

  // Subtitle
  ctx.fillStyle = 'rgba(198,242,78,0.6)'
  ctx.font = '14px monospace'
  ctx.fillText('dauntexlabs · sample image', PNG_W / 2, PNG_H / 2 + 18)

  // Timestamp
  ctx.fillStyle = 'rgba(198,242,78,0.35)'
  ctx.font = '11px monospace'
  ctx.fillText(new Date().toISOString(), PNG_W / 2, PNG_H / 2 + 46)
}

/* ── component ──────────────────────────────────────────────────────────── */

export default function FileGenerators() {
  const [fileType, setFileType] = useState<FileType>('csv')
  const [rows, setRows] = useState('10')
  const [content, setContent] = useState('')
  const [pngUrl, setPngUrl] = useState<string | null>(null)

  const canvasRef = useRef<HTMLCanvasElement>(null)
  const prevPngUrl = useRef<string | null>(null)

  const cfg = FILE_CONFIGS[fileType]

  const generateText = useCallback((type: FileType, rowCount: number): string => {
    switch (type) {
      case 'csv':      return generateCSV(rowCount)
      case 'json':     return generateJSON(rowCount)
      case 'xml':      return generateXML(rowCount)
      case 'html':     return generateHTML()
      case 'markdown': return generateMarkdown()
      case 'text':     return generatePlainText()
      default:         return ''
    }
  }, [])

  function handleGenerate() {
    if (fileType === 'png') {
      const canvas = canvasRef.current
      if (!canvas) return
      drawCanvas(canvas)
      // Revoke old object URL
      if (prevPngUrl.current) URL.revokeObjectURL(prevPngUrl.current)
      canvas.toBlob((blob) => {
        if (!blob) return
        const url = URL.createObjectURL(blob)
        prevPngUrl.current = url
        setPngUrl(url)
      }, 'image/png')
      setContent('')
    } else {
      const n = Math.max(1, Math.min(500, parseInt(rows) || 10))
      const text = generateText(fileType, n)
      setContent(text)
      setPngUrl(null)
    }
  }

  // Regenerate when type changes to keep preview fresh
  useEffect(() => {
    setContent('')
    setPngUrl(null)
  }, [fileType])

  function downloadPng() {
    if (!pngUrl) return
    const a = document.createElement('a')
    a.href = pngUrl
    a.download = 'sample-image.png'
    document.body.appendChild(a)
    a.click()
    document.body.removeChild(a)
  }

  return (
    <>
      <Toolbar>
        <Field label="File type">
          <Select
            value={fileType}
            onChange={(v) => setFileType(v as FileType)}
            options={FILE_TYPE_OPTIONS}
          />
        </Field>
        {cfg.hasRows && (
          <Field label="Rows">
            <TextInput value={rows} onChange={setRows} type="number" placeholder="10" />
          </Field>
        )}
        <Button variant="primary" onClick={handleGenerate}>
          Generate
        </Button>
      </Toolbar>

      {/* Hidden canvas for PNG generation */}
      <canvas ref={canvasRef} style={{ display: 'none' }} />

      {fileType === 'png' ? (
        <IO>
          <Panel
            title="PNG preview"
            actions={
              pngUrl ? (
                <Button variant="ghost" onClick={downloadPng}>
                  download PNG
                </Button>
              ) : undefined
            }
          >
            {pngUrl ? (
              <img
                src={pngUrl}
                alt={`Generated ${PNG_W}×${PNG_H} PNG`}
                style={{
                  maxWidth: '100%',
                  borderRadius: 4,
                  border: '1px solid var(--line)',
                  display: 'block',
                }}
              />
            ) : (
              <span style={{ color: 'var(--mute)', fontSize: '0.85rem' }}>
                Click Generate to produce a PNG image.
              </span>
            )}
          </Panel>
        </IO>
      ) : (
        <IO>
          <Panel
            title={`${cfg.label.toLowerCase()} preview`}
            actions={
              content ? (
                <>
                  <CopyButton text={content} />
                  <DownloadButton
                    text={content}
                    filename={`sample.${cfg.ext}`}
                    mime={cfg.mime}
                    label={`download .${cfg.ext}`}
                  />
                </>
              ) : undefined
            }
          >
            <TextArea
              value={content}
              readOnly
              placeholder={`Click Generate to produce a sample ${cfg.label} file…`}
              rows={18}
            />
          </Panel>
        </IO>
      )}
    </>
  )
}
