'use client'

import { useState } from 'react'
import {
  Toolbar,
  IO,
  Panel,
  TextArea,
  Toggle,
  CopyButton,
  DownloadButton,
  Notice,
} from '@/components/ui/kit'

// ── Gitignore templates ──────────────────────────────────────────────────────

const TEMPLATES: { key: string; label: string; content: string }[] = [
  {
    key: 'Node',
    label: 'Node',
    content: `# Dependency directories
node_modules/
jspm_packages/

# Build output
dist/
build/
out/
.next/
.nuxt/
.output/
.vite/

# Logs
logs/
*.log
npm-debug.log*
yarn-debug.log*
yarn-error.log*
pnpm-debug.log*

# Runtime / cache
.npm
.eslintcache
.node_repl_history
.cache/
.parcel-cache/

# Environment files
.env
.env.local
.env.*.local

# Coverage
coverage/
.nyc_output/

# Optional — yarn / pnpm
.yarn/cache
.yarn/unplugged
.yarn/build-state.yml
.pnp.*
package-lock.json.bak`,
  },
  {
    key: 'Python',
    label: 'Python',
    content: `# Byte-compiled / optimized / DLL files
__pycache__/
*.py[cod]
*$py.class

# Virtual environments
.venv/
venv/
env/
ENV/
.env/

# Distribution / packaging
dist/
build/
*.egg-info/
*.egg
.eggs/
wheels/

# Installer logs
pip-log.txt
pip-delete-this-directory.txt

# Unit test / coverage
.tox/
.coverage
htmlcov/
.pytest_cache/
.cache/
nosetests.xml
coverage.xml

# Type checking
.mypy_cache/
.dmypy.json
.pyre/

# Jupyter notebooks
.ipynb_checkpoints/

# Poetry
poetry.lock`,
  },
  {
    key: 'Java',
    label: 'Java',
    content: `# Compiled class files
*.class

# Log files
*.log

# Package files
*.jar
*.war
*.nar
*.ear
*.zip
*.tar.gz
*.rar

# Build output
target/
build/
out/

# Maven
.mvn/timing.properties
.mvn/wrapper/maven-wrapper.jar

# Gradle
.gradle/
**/build/
!src/**/build/
gradle-app.setting
!gradle-wrapper.jar
!gradle-wrapper.properties

# IDE
.idea/
*.iws
*.iml
*.ipr`,
  },
  {
    key: 'Go',
    label: 'Go',
    content: `# Binaries
*.exe
*.exe~
*.dll
*.so
*.dylib
/bin/

# Test binary (built from go test -c)
*.test

# Output of go coverage tool
*.out
coverage.html

# Go workspace file
go.work.sum

# Vendor directory (if not committed)
/vendor/

# Build cache
/tmp/`,
  },
  {
    key: 'Rust',
    label: 'Rust',
    content: `# Build output
/target/
Cargo.lock.bak

# Backup files generated by rustfmt
**/*.rs.bk

# MSVC Windows builds
*.pdb

# Profiling
perf.data
perf.data.old

# Test output
/test-results/`,
  },
  {
    key: 'macOS',
    label: 'macOS',
    content: `# macOS metadata
.DS_Store
.DS_Store?
._*
.Spotlight-V100
.Trashes
.AppleDouble
.LSOverride
Icon\r

# Thumbnails
ehthumbs.db
Thumbs.db

# Volume icons
.VolumeIcon.icns
.com.apple.timemachine.donotpresent

# Finders
.fseventsd
.TemporaryItems
.apdisk`,
  },
  {
    key: 'Windows',
    label: 'Windows',
    content: `# Windows thumbnails
Thumbs.db
Thumbs.db:encryptable
ehthumbs.db
ehthumbs_vista.db

# Dump files
*.stackdump

# Folder config
[Dd]esktop.ini
$RECYCLE.BIN/
*.cab
*.msi
*.msix
*.msm
*.msp
*.lnk`,
  },
  {
    key: 'Linux',
    label: 'Linux',
    content: `# Temp and backup files
*~
.fuse_hidden*
.directory
.Trash-*
.nfs*

# KDE
.konsole-history`,
  },
  {
    key: 'VisualStudioCode',
    label: 'VS Code',
    content: `# VS Code workspace settings (keep settings.json if sharing config)
.vscode/*
!.vscode/settings.json
!.vscode/tasks.json
!.vscode/launch.json
!.vscode/extensions.json
!.vscode/*.code-snippets

# Local History extension
.history/

# Built Visual Studio Code Extensions
*.vsix`,
  },
  {
    key: 'JetBrains',
    label: 'JetBrains',
    content: `# JetBrains IDE files
.idea/
*.iml
*.iws
*.ipr
out/
.idea_modules/
atlassian-ide-plugin.xml
com_crashlytics_export_strings.xml
crashlytics.properties
crashlytics-build.properties
fabric.properties

# CMake
cmake-build-*/

# Gradle / Maven caches (managed by IDE)
.gradle/
.mvn/

# Shelf
shelf/`,
  },
]

const TEMPLATE_MAP = Object.fromEntries(TEMPLATES.map((t) => [t.key, t]))

export default function GitignoreGenerator() {
  const [selected, setSelected] = useState<Record<string, boolean>>({})

  function toggle(key: string, on: boolean) {
    setSelected((prev) => ({ ...prev, [key]: on }))
  }

  const output = TEMPLATES.filter((t) => selected[t.key])
    .map((t) => `# === ${t.key} ===\n\n${t.content.trim()}`)
    .join('\n\n\n')

  const activeCount = Object.values(selected).filter(Boolean).length

  return (
    <>
      <Toolbar>
        <span style={{ fontFamily: 'var(--font-mono)', fontSize: '0.75rem', color: 'var(--mute)', letterSpacing: '0.05em' }}>
          {activeCount === 0 ? 'Select templates below' : `${activeCount} template${activeCount > 1 ? 's' : ''} selected`}
        </span>
      </Toolbar>

      <div
        style={{
          display: 'flex',
          flexWrap: 'wrap',
          gap: '0.75rem',
          padding: '1rem',
          border: '1px solid var(--line)',
          borderRadius: '4px',
          marginBottom: '1rem',
          background: 'var(--ink-850)',
        }}
      >
        {TEMPLATES.map((t) => (
          <Toggle
            key={t.key}
            checked={!!selected[t.key]}
            onChange={(on) => toggle(t.key, on)}
            label={t.label}
          />
        ))}
      </div>

      {activeCount === 0 ? (
        <Notice kind="info">Select one or more templates above to generate your .gitignore.</Notice>
      ) : (
        <IO>
          <Panel
            title=".gitignore"
            actions={
              <>
                <CopyButton text={output} />
                <DownloadButton text={output} filename=".gitignore" />
              </>
            }
          >
            <TextArea value={output} readOnly rows={20} />
          </Panel>
        </IO>
      )}
    </>
  )
}
